// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blist/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryBListByNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryBListByNameRequest) Reset()         { *m = QueryBListByNameRequest{} }
func (m *QueryBListByNameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBListByNameRequest) ProtoMessage()    {}
func (*QueryBListByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a53b4a48233b45, []int{0}
}
func (m *QueryBListByNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBListByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBListByNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBListByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBListByNameRequest.Merge(m, src)
}
func (m *QueryBListByNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBListByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBListByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBListByNameRequest proto.InternalMessageInfo

type QueryBListByNameResponse struct {
	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (m *QueryBListByNameResponse) Reset()         { *m = QueryBListByNameResponse{} }
func (m *QueryBListByNameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBListByNameResponse) ProtoMessage()    {}
func (*QueryBListByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a53b4a48233b45, []int{1}
}
func (m *QueryBListByNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBListByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBListByNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBListByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBListByNameResponse.Merge(m, src)
}
func (m *QueryBListByNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBListByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBListByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBListByNameResponse proto.InternalMessageInfo

func (m *QueryBListByNameResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type QueryBListRequest struct {
}

func (m *QueryBListRequest) Reset()         { *m = QueryBListRequest{} }
func (m *QueryBListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBListRequest) ProtoMessage()    {}
func (*QueryBListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a53b4a48233b45, []int{2}
}
func (m *QueryBListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBListRequest.Merge(m, src)
}
func (m *QueryBListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBListRequest proto.InternalMessageInfo

type QueryBListResponse struct {
	Blist []string `protobuf:"bytes,1,rep,name=blist,proto3" json:"blist,omitempty"`
}

func (m *QueryBListResponse) Reset()         { *m = QueryBListResponse{} }
func (m *QueryBListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBListResponse) ProtoMessage()    {}
func (*QueryBListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a53b4a48233b45, []int{3}
}
func (m *QueryBListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBListResponse.Merge(m, src)
}
func (m *QueryBListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBListResponse proto.InternalMessageInfo

func (m *QueryBListResponse) GetBlist() []string {
	if m != nil {
		return m.Blist
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryBListByNameRequest)(nil), "iritamod.blist.QueryBListByNameRequest")
	proto.RegisterType((*QueryBListByNameResponse)(nil), "iritamod.blist.QueryBListByNameResponse")
	proto.RegisterType((*QueryBListRequest)(nil), "iritamod.blist.QueryBListRequest")
	proto.RegisterType((*QueryBListResponse)(nil), "iritamod.blist.QueryBListResponse")
}

func init() { proto.RegisterFile("blist/query.proto", fileDescriptor_c2a53b4a48233b45) }

var fileDescriptor_c2a53b4a48233b45 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x31, 0x4f, 0x32, 0x41,
	0x10, 0xbd, 0xe3, 0xfb, 0x30, 0xb0, 0x85, 0x91, 0x0d, 0x09, 0x48, 0xf4, 0xc0, 0x2b, 0x94, 0x58,
	0xdc, 0x8a, 0x16, 0x26, 0x96, 0xb4, 0x1a, 0x13, 0xaf, 0xb4, 0xdb, 0x93, 0xc9, 0xb1, 0x86, 0xdd,
	0x3d, 0x6e, 0xf7, 0x88, 0xc4, 0xd8, 0x58, 0xd9, 0x90, 0x98, 0xf8, 0x07, 0xf8, 0x39, 0x96, 0x24,
	0x36, 0x96, 0x06, 0x2c, 0xfc, 0x19, 0x86, 0x3d, 0x08, 0xa8, 0x41, 0xbb, 0x99, 0xbc, 0x37, 0xef,
	0xcd, 0x9b, 0x5d, 0x54, 0x08, 0x3a, 0x4c, 0x69, 0xd2, 0x4d, 0x20, 0xee, 0x7b, 0x51, 0x2c, 0xb5,
	0xc4, 0xeb, 0x2c, 0x66, 0x9a, 0x72, 0xd9, 0xf2, 0x0c, 0x56, 0x29, 0x86, 0x32, 0x94, 0x06, 0x22,
	0xd3, 0x2a, 0x65, 0x55, 0xb6, 0x42, 0x29, 0xc3, 0x0e, 0x10, 0x1a, 0x31, 0x42, 0x85, 0x90, 0x9a,
	0x6a, 0x26, 0x85, 0x4a, 0x51, 0xf7, 0x18, 0x95, 0x2e, 0xa6, 0x92, 0xcd, 0x33, 0xa6, 0x74, 0xb3,
	0x7f, 0x4e, 0x39, 0xf8, 0xd0, 0x4d, 0x40, 0x69, 0x8c, 0xd1, 0x7f, 0x41, 0x39, 0x94, 0xed, 0x9a,
	0x5d, 0xcf, 0xfb, 0xa6, 0x3e, 0xc9, 0x3d, 0x0c, 0xab, 0xd6, 0xc7, 0xb0, 0x6a, 0xb9, 0x07, 0xa8,
	0xfc, 0x73, 0x50, 0x45, 0x52, 0x28, 0xc0, 0x45, 0x94, 0x85, 0x1b, 0xa6, 0xb4, 0x19, 0xcd, 0xf9,
	0x69, 0xe3, 0x6e, 0xa3, 0xc2, 0x62, 0x62, 0x66, 0xb2, 0x24, 0xb8, 0x8f, 0xf0, 0x32, 0xbc, 0x90,
	0x32, 0xe1, 0xca, 0x76, 0xed, 0x5f, 0x3d, 0xef, 0xa7, 0xcd, 0xe1, 0x20, 0x83, 0xb2, 0x86, 0x8c,
	0x07, 0x36, 0xda, 0xf8, 0xbe, 0x07, 0xde, 0xf3, 0xbe, 0x5e, 0xc6, 0x5b, 0x11, 0xb1, 0x52, 0xff,
	0x9b, 0x98, 0xee, 0xe1, 0xee, 0xde, 0xbf, 0xbc, 0x3f, 0x65, 0x6a, 0xd8, 0x21, 0xa0, 0xdb, 0x10,
	0x73, 0x26, 0x34, 0x81, 0x1e, 0x27, 0xbd, 0x06, 0x49, 0x1f, 0xe6, 0x76, 0x7a, 0x9f, 0x3b, 0xac,
	0x11, 0x5a, 0x68, 0xe0, 0x9d, 0xd5, 0xfa, 0xf3, 0x15, 0xdc, 0xdf, 0x28, 0x33, 0xf3, 0xaa, 0x31,
	0xdf, 0xc4, 0xa5, 0x15, 0xe6, 0xcd, 0xd3, 0xe7, 0xb1, 0x63, 0x8f, 0xc6, 0x8e, 0xfd, 0x36, 0x76,
	0xec, 0xc7, 0x89, 0x63, 0x8d, 0x26, 0x8e, 0xf5, 0x3a, 0x71, 0xac, 0xcb, 0x46, 0xc8, 0x74, 0x3b,
	0x09, 0xbc, 0x2b, 0xc9, 0x49, 0xc0, 0xa8, 0xb8, 0x66, 0x40, 0x19, 0x99, 0x5b, 0x12, 0x2e, 0x5b,
	0x49, 0x07, 0xd4, 0x2c, 0x83, 0xee, 0x47, 0xa0, 0x82, 0x35, 0xf3, 0x33, 0x8e, 0x3e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xe8, 0x64, 0x9e, 0x7b, 0x72, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryBListByName(ctx context.Context, in *QueryBListByNameRequest, opts ...grpc.CallOption) (*QueryBListByNameResponse, error)
	QueryBList(ctx context.Context, in *QueryBListRequest, opts ...grpc.CallOption) (*QueryBListResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryBListByName(ctx context.Context, in *QueryBListByNameRequest, opts ...grpc.CallOption) (*QueryBListByNameResponse, error) {
	out := new(QueryBListByNameResponse)
	err := c.cc.Invoke(ctx, "/iritamod.blist.Query/QueryBListByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryBList(ctx context.Context, in *QueryBListRequest, opts ...grpc.CallOption) (*QueryBListResponse, error) {
	out := new(QueryBListResponse)
	err := c.cc.Invoke(ctx, "/iritamod.blist.Query/QueryBList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryBListByName(context.Context, *QueryBListByNameRequest) (*QueryBListByNameResponse, error)
	QueryBList(context.Context, *QueryBListRequest) (*QueryBListResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryBListByName(ctx context.Context, req *QueryBListByNameRequest) (*QueryBListByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBListByName not implemented")
}
func (*UnimplementedQueryServer) QueryBList(ctx context.Context, req *QueryBListRequest) (*QueryBListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBList not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryBListByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBListByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryBListByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iritamod.blist.Query/QueryBListByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryBListByName(ctx, req.(*QueryBListByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryBList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryBList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iritamod.blist.Query/QueryBList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryBList(ctx, req.(*QueryBListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iritamod.blist.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryBListByName",
			Handler:    _Query_QueryBListByName_Handler,
		},
		{
			MethodName: "QueryBList",
			Handler:    _Query_QueryBList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blist/query.proto",
}

func (m *QueryBListByNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBListByNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBListByNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBListByNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBListByNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBListByNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exist {
		i--
		if m.Exist {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryBListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Blist) > 0 {
		for iNdEx := len(m.Blist) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Blist[iNdEx])
			copy(dAtA[i:], m.Blist[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Blist[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryBListByNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBListByNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Exist {
		n += 2
	}
	return n
}

func (m *QueryBListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryBListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Blist) > 0 {
		for _, s := range m.Blist {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryBListByNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBListByNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBListByNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBListByNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBListByNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBListByNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exist", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exist = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blist = append(m.Blist, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
